#! /bin/sh
export GDK_SCALE=2
export GDK_DPI_SCALE=0.6

#xrandr --output Virtual1 --mode 3840x2160

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bash ~/.config/polybar/launch.sh --forest &

feh --bg-fill -z .walls/ &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a "*Code*" desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom &

conky -c .config/conky/Style_Retro.conkyrc &

#~/.config/spectrumyzer/spectrumyzer.py &

#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
